#!/usr/bin/env bash
mkdir -p dist
echo "offset.js ..."
./node_modules/.bin/lsc -cpb src/offset.ls > dist/offset.js
echo "minifying offset.js ..."
./node_modules/.bin/uglifyjs dist/offset.js -m -c > dist/offset.min.js
echo "done."
